### ISSUE TITLE
Error after a reboot

### ISSUE THREAD

**Issue by Paul-dH** [Paul-dH/Home-Assisant-Sensor-OvApi#3]
Error happening after a reboot of Hass, could also be the fact that it was in the evening and the array of departure times is now smaller than 5 (3 at the moment), as configured below:
https://github.com/Paul-dH/Home-Assisant-Sensor-OvApi/blob/9f0b25566a30b61b445516bd31b8909b3b4e8040/ovapi.py#L173

Error message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 347, in async_device_update
    await self.async_update()
  File "/config/custom_components/sensor/ovapi.py", line 197, in async_update
    self._departure = stops_list[0]["TargetDepartureTime"].strftime('%H:%M')
IndexError: list index out of range
```

**Comment by pippyn** [comment]
FIXED in latest pull request

**Comment by Paul-dH** [comment]
The error is fixed indeed after a reboot, I'll close the issue tomorrow. The log should stay clean in the night when there are no departures after 01:00 hour.

**Comment by Paul-dH** [comment]
Issue is fixed in latest pull request.
