### ISSUE TITLE
Error on device update when using stop_code / route_code

### ISSUE THREAD

**Issue by Toets** [Paul-dH/Home-Assisant-Sensor-OvApi#37]
I get an error when I use the combination of stop_code and route_code.  To be sure I used your first example as a test. This example generates the exact same error :

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 729, in async_device_update
    await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ovapi/sensor.py", line 213, in update
    stops = itertools.islice(data[self._stop_code][self._route_code]['Passes'].values(), 50)
KeyError: '32009505'

**Comment by IIIdefconIII** [comment]
Im not sturen bro, i used it kijken 2 years ago and Nederland looked at it again


Met vriendelijke groet,



Thomas van Dalen

E: ***@***.******@***.***>

T: +316 30 929 009<tel:+31630929009>

________________________________
From: Toets ***@***.***>
Sent: Friday, January 13, 2023 10:31:04 PM
To: Paul-dH/Home-Assisant-Sensor-OvApi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Paul-dH/Home-Assisant-Sensor-OvApi] Error on device update when using stop_code / route_code (Issue #37)


I get an error when I use the combination of stop_code and route_code. To be sure I used your first example as a test. This example generates the exact same error :

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 729, in async_device_update
await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ovapi/sensor.py", line 213, in update
stops = itertools.islice(data[self._stop_code][self._route_code]['Passes'].values(), 50)
KeyError: '32009505'
